name: Windows Build FNKNGT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Setup and Build
        run: |
          cinst haxe --version 4.1.5 -y
          RefreshEnv
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          RefreshEnv
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git
          haxelib list
          haxelib run lime build windows
          
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: export/release/windows/bin